SERVICE_ACCOUNT_ID = "firebase-adminsdk-6z854@wedding-41b3e.iam.gserviceaccount.com"
BASE_FILEPATH = "src/backend/data/"
GUESTS_FILEPATH = f"{BASE_FILEPATH}guests.txt"
FAMILIES_FILEPATH = f"{BASE_FILEPATH}families.json"
PASSWORDS_FILEPATH = f"{BASE_FILEPATH}passwords.txt"